create table voters_ID
(
	name varchar(50) ,
	id int IDENTITY(1,1),
	age int,
)

INSERT INTO voters_ID
SELECT 'ARANI',33

INSERT INTO voters_ID
SELECT 'RANI',35

INSERT INTO voters_ID
SELECT 'KITTU',36

SELECT * FROM voters_ID

DELETE FROM voters_ID WHERE AGE=33

INSERT INTO voters_ID
SELECT 'ARANI',33

TRUNCATE TABLE VOTERS_ID

INSERT INTO voters_ID
SELECT 'ARANI',33

SELECT * INTO VOTERSIDENTITY FROM voters_ID


SELECT * FROM VOTERSIDENTITY
